name: Main CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  full-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Build project
        run: npm run build
        
      - name: Run type checking
        run: npm run typecheck
        
      - name: Run full test suite
        run: npm run test:ci
        
      - name: Run performance tests
        run: npm run test:performance
        
      - name: Run security scan
        run: npm audit --audit-level=high
        
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: true
          
      # Future: Deployment preparation
      # - name: Prepare deployment artifacts
      #   run: npm run prepare:deploy